### ISSUE TITLE
Use upstream Sourcify images as a dependency

### ISSUE THREAD

**Issue by acuarica** [hashgraph/hedera-sourcify#147]
### Problem

Instead of maintaining our own fork of the verification service, use the images provided by upstream Sourcify directly. This will allow us to avoid duplicating efforts and incorporate new features easily.

For Hedera verification, we decided to directly consume `server` and `repository` images from Sourcify upstream. Given that the `ui` changes might be too Hedera specific, we decided to keep our `ui` fork with custom modifications.

### Solution

The following is a list a features that upstream Sourcify should implement in order to use their images directly.

### Server image

- [x] `dryrun` query parameter _used in hashscan.io_ https://github.com/hashgraph/hedera-sourcify/pull/92 https://github.com/hashgraph/hedera-sourcify/pull/111 https://github.com/hashgraph/hedera-sourcify/pull/112. Tracking issue https://github.com/ethereum/sourcify/issues/1319.
- [x] TODO in another PR. Verification `/metrics` https://github.com/hashgraph/hedera-sourcify/pull/131. Tracking issue https://github.com/ethereum/sourcify/issues/1320.
- [x] Chains configuration https://github.com/hashgraph/hedera-sourcify/pull/12
- [x] Customize `servers` dropdown in OpenAPI docs https://github.com/hashgraph/hedera-sourcify/pull/118. Tracking issue https://github.com/ethereum/sourcify/issues/1345.
<img width="632" alt="image" src="https://github.com/hashgraph/hedera-sourcify/assets/4592980/71de5140-2251-41cc-9f55-50959cded57c">

### Repository image (and `select-contract-form` UI)

https://repository-verify.hashscan.io/select-contract/ _vs_ https://repo.sourcify.dev/select-contract/

- [x] Chain configuration https://github.com/hashgraph/hedera-sourcify/pull/12
<img width="503" alt="image" src="https://github.com/hashgraph/hedera-sourcify/assets/4592980/795b458a-0f4c-4f7a-83d9-a5161adba036">

- [x] Allows users to lookup with non-checksummed addresses https://github.com/hashgraph/hedera-sourcify/pull/100. Tracking issue https://github.com/ethereum/sourcify/issues/1341.

- [x] Building image on Apple M-chips https://github.com/hashgraph/hedera-sourcify/pull/104

- [x] Customize _Open repo in Remix_ link, _i.e._, either enable or disable it https://github.com/hashgraph/hedera-sourcify/issues/65

- [x] Fix default chain ID for during verification lookup https://github.com/hashgraph/hedera-sourcify/issues/64

### UI image _just for completion, we continue to use our own fork_

https://verify.hashscan.io/ _vs_ https://sourcify.dev/#/verifier

Given that it might be more difficult to push our customizations in the UI, we might keep our fork of the UI. Thus, these issues are less relevant.

- [x] CSS/HTML customizations _links and logo_ https://github.com/hashgraph/hedera-sourcify/pull/49
<img width="1084" alt="image" src="https://github.com/hashgraph/hedera-sourcify/assets/4592980/695320d5-92f6-4992-b788-2ee38f332175">

- [x] Chain configuration https://github.com/hashgraph/hedera-sourcify/pull/12
<img width="600" alt="image" src="https://github.com/hashgraph/hedera-sourcify/assets/4592980/8523bc0a-bf80-4af6-affc-443eea0886d8">

- [x] Compatible terminology with mirror-node-explorer https://github.com/hashgraph/hedera-sourcify/pull/59

- [x] Removed the Sourcify landing page
