### ISSUE TITLE
Remove `ui`'s landing page and its dependencies

### ISSUE THREAD

**Issue by acuarica** [hashgraph/hedera-sourcify#160]
The landing page of Sourcify https://sourcify.dev/ is part of the `ui` react app. However, instead of a landing page, Hedera verification uses the verifier page directly.

To avoid polluting the react app with unused pages and to make the `ui` leaner, remove the landing page and it's dependencies.
```[tasklist]
### Tasks
- [x] Remove `ui/src/pages/LandingPage`
- [x] Review and remove any dangling file pointed by `LandingPage/*`
- [x] Review and remove dangling `package.json`'s dependencies
- [x] Review and remove and dangling assets
```
