### ISSUE TITLE
Sourcify v2 upstream upgrade

### ISSUE THREAD

**Issue by acuarica** [hashgraph/hedera-sourcify#264]
Upgrade to DB version of Sourcify https://github.com/ethereum/sourcify/issues/1545 to unblock a more feature rich verification experience.

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-sourcify/issues/138
- [ ] https://github.com/hashgraph/hedera-sourcify/issues/210
- [ ] https://github.com/hashgraph/hedera-sourcify/issues/218
```

**Comment by Ferparishuertas** [comment]
Sourcify has been removed and we depend on the community instance
